name: bumaco_aios
description: An e-commerce.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.7+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.3.0
  firebase_analytics: ^8.3.4
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.4
  flutter_staggered_grid_view: ^0.4.0
  flutter_facebook_auth: ^3.5.2
  firebase_auth: ^3.1.1
  flutter_google_places: ^0.3.0
  location: ^4.3.0
  get: ^4.6.1
  dio: ^4.0.4
  floor: ^1.1.0
  uuid: ^3.0.4
  http: ^0.13.3
  equatable: ^2.0.3
  jwt_decoder: ^2.0.1
  get_storage: ^2.0.3
  velocity_x: ^3.3.0
  google_fonts: ^2.1.0
  flutter_sound: ^8.3.12
  transparent_image: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_bloc: ^8.0.0
  flare_flutter: ^3.0.2
  multi_select_flutter: ^4.0.0
  share: ^2.0.4
  path_provider: ^2.0.7
  flutter_cache_manager: ^3.1.2
  cached_network_image: ^3.1.0
  socket_io_client: ^1.0.1
  video_player: ^2.2.6
  razorpay_flutter: ^1.2.7
  chewie: ^1.1.0
  webview_flutter: ^2.3.1
  json_annotation: ^4.4.0
  flutter_dotenv: ^5.0.2
  lottie: ^1.2.1
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.1.0
  build_runner: ^2.0.0
  json_serializable: ^6.1.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.pro
    - assets/images/
    - assets/icons/
    - assets/rive/
    - assets/lottie/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri.ttf
        - asset: assets/fonts/Calibri Bold.ttf
          style: italic
    - family: Samantha
      fonts:
        - asset: assets/fonts/Samantha.ttf

